apiVersion: apps/v1
kind: Deployment
metadata:
  name: synthetic-service-chain
  namespace: ingress-nginx
  labels:
    app: synthetic-service-chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synthetic-service-chain
  template:
    metadata:
      labels:
        app: synthetic-service-chain
        namespace: ingress-nginx
    spec:
      containers:
        - name: synthetic-service-chain
          image: michelgokan/synthetic-service-chain
          env:
            - name: NEXT_SERVICES_ADDRESSES #comma separated
              value: ""
            - name: NAME
              value: "<NO NAME>" #set service name here
          ports:
            - containerPort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: synthetic-service-chain
  namespace: ingress-nginx
  labels:
    app: synthetic-service-chain
spec:
  ports:
  - port: 30005
    targetPort: 30005
    protocol: TCP
    name: http
  selector:
    app: synthetic-service-chain

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: synthetic-service-chain
  namespace: ingress-nginx
  annotations:
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
     nginx.org/client-max-body-size: "10000m"
spec:
  tls:
    - secretName: tls-certificate
  rules:
    - http:
        paths:
          - path: /workload
            backend:
              serviceName: synthetic-service-chain
              servicePort: 30005
