apiVersion: apps/v1
kind: Deployment
metadata:
  name: s8
  namespace: ingress-nginx
  labels:
    app: s8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s8
  template:
    metadata:
      labels:
        app: s8
        namespace: ingress-nginx
    spec:
      containers:
        - name: s8
          image: michelgokan/synthetic-service-mesh
          env:
            - name: NEXT_SERVICES_ADDRESSES
              value: ""
            - name: NAME
              value: "s8"
          ports:
            - containerPort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: s8
  namespace: ingress-nginx
  labels:
    app: synthetic-service-mesh
spec:
  ports:
  - port: 30012
    targetPort: 30005
    protocol: TCP
    name: http
  selector:
    app: s8

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: s8
  namespace: ingress-nginx
  annotations:
     nginx.ingress.kubernetes.io/ssl-redirect: "false"
     nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
     nginx.ingress.kubernetes.io/proxy-body-size: "10000m"
     nginx.org/client-max-body-size: "10000m" 
spec:
  tls:
    - secretName: tls-certificate
  rules:
    - http:
        paths:
          - path: /s8
            backend:
              serviceName: s8
              servicePort: 30005
